# =====================================================
# SonarCloud Configuration
# =====================================================

sonar.organization=jyotics24
sonar.projectKey=jyotics24_cloud-native-order-tracking-platform-project

# =====================================================
# Project Information
# =====================================================

sonar.projectName=Cloud-Native Order Tracking Platform
sonar.projectVersion=1.0

# =====================================================
# Source Code
# =====================================================

sonar.sources=app/backend

# =====================================================
# Tests
# =====================================================

sonar.tests=app/backend
sonar.test.inclusions=**/test_*.py

# =====================================================
# Python
# =====================================================

sonar.python.version=3.11

# =====================================================
# Coverage Report
# =====================================================

sonar.python.coverage.reportPaths=app/backend/coverage.xml

# =====================================================
# Exclusions
# =====================================================

sonar.exclusions=**/venv/**,**/__pycache__/**