# ==================================================
# SonarCloud Project Configuration
# ==================================================

sonar.organization=jyotics24

sonar.projectKey=jyotics24_cloud-native-order-tracking-platform-project

sonar.projectName=cloud-native-order-tracking-platform-project

sonar.projectVersion=1.0

sonar.sources=app/backend

sonar.tests=app/backend

sonar.test.inclusions=**/test_*.py

sonar.python.version=3

sonar.sourceEncoding=UTF-8